[workspace]
authors = ["Brian Grenier <grenierb96@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojo-hack"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=25.5.0.dev2025062705,<26"
